name: Windrose
channels:
  - conda-forge
  - defaults
dependencies:
  - python>3.6
  - notebook>5.2
  - jupyter_dashboards
  - jupyter_dashboards_bundlers
  - matplotlib
  - windrose
  - netCDF4
  - wrf-python
  - ipywidgets=7
  - numpy
  - IPython.display
  - matplotlib.animation
